name: Deploy React to cPanel
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Install and Build
      run: |
        npm install --legacy-peer-deps
        npm run build
        
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/              
        server-dir: ./                 # Menggunakan ./ karena akun FTP Anda sudah dilempar langsung ke folder 'user'
        port: 21
        protocol: ftp
