name: Deploy React to cPanel
on:
  push:
    branches:
      - main  # Ganti dengan 'master' jika branch utama Anda di GitHub adalah master
  workflow_dispatch: # Fitur tambahan agar Anda bisa klik "Run workflow" secara manual lewat tab Actions

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Install and Build
      run: |
        npm install --legacy-peer-deps
        npm run build
        
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/              # Jika nanti error "dir ./dist/ does not exist", ganti menjadi ./build/
        server-dir: ./public_html/      # PERBAIKAN: File langsung masuk ke folder utama website Anda
        port: 21
        protocol: ftp
